version: '3.3'
services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: 'pokemonDB'
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql'
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo_db:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongo_db:/data/db
  # Names our volume
  app:
    container_name: game_service_container
    build: ./game_service
    depends_on:
        - mysql_db
    ports:
        - "8000:8000"
  app2:
    container_name: gateway_container
    build: ./gateway
    ports:
      - '8001:8001'
volumes:
  mysql-db:
  mongo_db: